# Generated by Django 6.1.1 on 2026-09-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, default='MATHEMATICS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
