# Generated by Django 6.1.1 on 2026-09-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_category_subject_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codePass',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tokens', to='core.user')),
            ],
        ),
    ]
